version: '2.6'

services:
 python10_yolov8: 
  build:
    context: . # Directory containing the Dockerfile
    dockerfile: Dockerfile #Name of the Dockerfile, if different
  devices:
    - /dev/nvidia0:/dev/nvidia0
  shm_size: '2gb'   #leads to numpycore memory error
  ports:
    - "5055:5055" # check port availability and Expose port on the host and container
  volumes:
    - .:/workspace #mount the current directory to /workspace in the container
  environment:
    # - Env=development # Example environment variable
    - TZ=Asia/Tokyo
    - JUPYTER_ENABLE_LAB=yes
    - NVIDIA_VISIBLE_DEVICES=all
  tty: true
  # runtime: nvidia
  deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
